sonar.projectKey=data-quality-monitor
sonar.projectName=Data Quality Monitoring
sonar.projectVersion=1.0
sonar.sources=src,dashboard
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
sonar.qualitygate.wait=true
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=reports/**,data/**,helm/**/templates/*.tpl,monitoring/grafana/dashboards/**,.tmp/**,.venv/**,.scannerwork/**,.pytest_cache/**,output/**,lab/**,jenkins/**,terraform/**/.terraform/**,**/__pycache__/**
