[data_quality_hosts]
lab-linux ansible_host=host.docker.internal ansible_port=2222 ansible_user=devops ansible_password=devops123! ansible_connection=ssh ansible_become=true ansible_python_interpreter=/usr/bin/python3 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[data_quality_hosts:vars]
docker_runtime_manage_engine=false
docker_compose_command=docker compose
dashboard_port=18501
dashboard_healthcheck_url=http://host.docker.internal:18501
docker_image=localhost:5001/data-quality-monitor:latest
